language: minimal
services:
- docker
before_install:
- docker pull sander1/xtables_geoip
script:
- mkdir ~/xt_build
- docker run -e LICENSE_KEY=$LICENSE_KEY --rm -v ~/xt_build:/xt_build sander1/xtables_geoip
after_success:
- bash push.sh
env:
  global:
  - secure: VBig3+Bs16i8cbFnqxo5lfXuLqvHHsQnY+At8o7eKtj+RL/ZGIRtnOYDPWEjr/w6K8mxm6aM6mgHpdaLSERCLJQzek74BVN/03wLZcKW4dTi8AUwpHhjA4XE6LONJ1JDmLAiag7pSzmWeoD76eJUTd4nmJCad4x/TBSi0J1O8TVLGhJk92YnK3ECDS1BdutE3AKjbevrKEIkFwmm4YwQBW3M0/zw8ptr2Ruq3KJS6I29Ggv39yyyZHNv1IBgRchpQOcW0FnCWM/6SZKx1XeSQz1iiAM5Tqqhon5Ujhq+VH9EZcMbIcrRI2JmG5CEL2nWU/hS6GTqHdydNwqYHojZHsWXwHWqODO0NcJDf6ADXuLye72w2WpLDmrANhmvL/C7XNGqtYX8bOQ1TAA8r/iHqgoDNr1zhg2ZgblttXZYHKNhiNYu9S0NjCZd8vMzXJh6Ju7sFrj+iw3OZyOX64fKPQ0TGHC3K9zSRHstvdc4MT24xRjeUXpYVN6HQQp3SORGwtPhUePE7So5avZ5AeNYzWhHXUO+iBuXQ5F6ad90wRiqwZ9We3FoL7Gti0H2O/2OG3J7JjQDOwqp3vDNxvv/myZ2UwB2X/ECxcQdSd+kmEB8gt9QHRN237em378tuWhf8lSlGT1xPYouKXY0yassOjz7tUng5jetQTE6JztIczE=
  - secure: pcK+vk+/Ytgbrgyg/3ouVf80AYLMOyCGd8dufV+xYMHlorrjCzQg2Xv4nneujrP7KwYhzuu5A2HEH02AEePqw4ln0APXEBEyvygM78RSgQi/WAL4TM+TZAia/yJdBPqqyOTo/9qujDAyPtB8Uvs53rNXech4XMFSOcruRME1YGN3b5sT1PJRosmjTJda1pZjRZlIR8iydTXTfrRARELHGMh5SwTyE8GIG63E2Ld0HdZI6iddOKNSv13hFc2uqeQ97aEuPDyn3EHOSGrk8F9JR9TpY1SGj6Zw7YpWpxW6UqpD6WfTpRX+rIECJN7bF6CYLCK1Ia6K0BZ2x7fEj8sJZ2Dt4qyirQ920BELyf2D5Uc2bWKEiyF+fCXzcoAHMcIR5ic8EK6aUMSaU3YMXjsPNjAGzC53HV7CPWaSGVcGTbdqQoDqdnasNSBp2djGMGucTf1ZGFD92rCKns5k4ZmM54WLkC5Cs49jHwCzXN5gu4R17z4HQVBtY8gBPXxK6ujBYl+8IUQsDSzliwR+WpUaxWJG0UEUhC/BoeiILztNUN40R/Shs42RDWnPEs4AvPjKVABUwl/fFaHHfhUkK1GoeVWLIf/xfnXzTmfVLiZ7y4eYVUa6Q5Cj01RLx9F0/o7ktflZjf5DQCleZYmNoNAtiwlntXiKH85O4RsFszGOA64=
